{
  "appName": "hello-dev",
  "userGivenName": "helloapp",
  "destNamespace": "hello-dev",
  "destServer": "https://kubernetes.default.svc",
  "srcPath": "helloapp-deployment/overlays/dev",
  "srcRepoURL": "https://github.com/patiyan-sukkasem/helloargo.git",
  "srcTargetRevision": "",
  "labels": null,
  "annotations": null
}
